version: 2.1

orbs:
  samvera: samvera/circleci-orb@1.0

jobs:
  lint:
    parameters:
      project:
        type: string
      ruby_version:
        type: string

    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>

    steps:
      - checkout

      - run:
          name: Check for 'master' branch
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
                echo "A branch named 'master' was found. Please remove it."
                echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]
      - samvera/cached_checkout

workflows:
  version: 2
  ci:
    jobs:
      - lint:
          project: parcel-browse-everything
          ruby_version: 2.7.7

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - lint:
          project: parcel-browse-everything
          ruby_version: 2.7.7
